
language: generic

notifications:
  email:
    recipients:
      - knutole@mapic.io
    on_success: change
    on_failure: change
  slack:
    rooms:
      - mapic-io:NKaii0z3tRkeDyXaDbRauRFp
    on_success: change
    on_failure: change

git:
  submodules: false

os:
  - linux
  - osx

install:
  # - sudo wget -qO- https://get.mapic.io/ | sh
  - sudo curl -sSL https://get.mapic.io  | sh

script:
  - mapic 
