
language: generic

notifications:
  email: false
  slack: mapic-io:NKaii0z3tRkeDyXaDbRauRFp

git:
  submodules: false

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: xenial
      sudo: required
    - os: linux
      dist: precise
      sudo: required
    - os: linux
      dist: zesty
      sudo: required
    - os: linux
      dist: yakkety
      sudo: required
    - os: linux
      dist: artful
      sudo: required
    - os: osx
      osx_image: xcode7.3.1
      sudo : required
    - os: osx
      osx_image: xcode8.3
      sudo : required

install:
  - sudo wget -qO- https://get.mapic.io/ | sh

script:
  - mapic 
